sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    # prevent google cloud from prompting for user input
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # download and install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl
  - gcloud components update kubectl
  # login to google cloud
  - gcloud auth activate-service-account --key-file service-account.json
  # set project
  - gcloud config set project fib-calculator-402313
  # set compute zone
  - gcloud config set compute/zone asia-southeast1-a
  # set cluster
  - gcloud container clusters get-credentials fib-calc-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t palsp/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true palsp/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main



