apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: client
          image: palsp/multi-client
          ports:
            - containerPort: 3000
