apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: web

resources:
- deployment.yaml
- service.yaml
images:
- name: palsp/multi-client
  newTag: 664db850c15f76259d123e11019d0addad70cb06
