apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: cu-connex-com-tls
spec:
  secretName: cu-connex-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cu-connex.com
  dnsNames:
    - cu-connex.com
    - www.cu-connex.com
